[package]
name = "nascent-os"
version = "0.1.0"
authors = ["RJ Rybarczyk <rj@rybar.tech>, Alex Segura <alex@lispm.dev>"]
edition = "2018"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
